name = "sora-watermark"
compatibility_date = "2024-06-30"
workers_dev = true

[[routes]]
pattern = "sora-watermark.clothpath.com/*"
zone_name = "clothpath.com"

[build]
command = "npm run build"

[assets]
directory = "./dist"
