export const ExampleComparison = () => {
  return (
    <div className="rounded-lg bg-white p-6 shadow-sm transition-colors dark:bg-gray-800">
      <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Example Result</h2>
      <p className="mt-2 text-sm text-gray-600 dark:text-gray-300">
        Compare the original clip against the watermarked output generated by this tool.
      </p>
      <div className="mt-4 grid gap-4 md:grid-cols-2">
        <div>
          <h3 className="text-sm font-medium text-gray-800 dark:text-gray-200">Original</h3>
          <video
            className="mt-2 w-full rounded-lg border border-gray-200 bg-black dark:border-gray-700"
            src="/original_video.mp4"
            autoPlay
            loop
            playsInline
            preload="metadata"
            muted
          />
        </div>
        <div>
          <h3 className="text-sm font-medium text-gray-800 dark:text-gray-200">Watermarked</h3>
          <video
            className="mt-2 w-full rounded-lg border border-gray-200 bg-black dark:border-gray-700"
            src="/watermarked_video.mp4"
            autoPlay
            loop
            playsInline
            preload="metadata"
            muted
          />
        </div>
      </div>
    </div>
  );
};
